name: '💫 Hyprland'

on:
  #schedule:
    #- cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday

  workflow_dispatch:  # click the button on Github repo!
    inputs:
      sync_test_mode: # Adds a boolean option that appears during manual workflow run for easy test mode config
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false
env:
  BRANCH: Hyprland

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: "Sync with Makrennel"
    steps:
    # REQUIRED step
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout target
      uses: actions/checkout@v4
      with:
        # optional: set the branch to checkout,
        # sync action checks out your 'target_sync_branch' anyway
        ref: ${{ env.BRANCH }}
        # REQUIRED if your upstream repo is private (see wiki)
        persist-credentials: false

    # REQUIRED step
    # Step 2: run the sync action
    - name: Sync changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: ${{ env.BRANCH }}
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: master
        upstream_sync_repo: Makrennel/hyprland-void
        #upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}
        target_branch_push_args: '--force'
        git_config_pull_rebase: true
        # Set test_mode true during manual dispatch to run tests instead of the true action!!
        test_mode: ${{ inputs.sync_test_mode }}

    # Step 3: Display a sample message based on the sync output var 'has_new_commits'
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}

    - name: Copy templates
      run: |
        echo '#TODO:'
        #cat common/shlibs >> ../void-packages/common/shlibs
        #cp -r --remove-destination srcpkgs/* ../void-packages/srcpkgs
